services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: datausers

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: npm run dev

  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./frontend:/app
  #   stdin_open: true
  #   tty: true

volumes:
  mongo-data:
